name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]  # You can add more versions here if needed.
        # For example: node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create .env file
      run:  echo "${{ secrets.PROD_ENV_FILE }}" > .env
	- run:  pm2 restart all
    # Uncomment if you need to build and run tests
    # - run: npm run build --if-present
    # - run: npm test